FROM node:16-alpine

# Установка правильных прав пользователя
RUN mkdir -p /app/node_modules && chmod 777 /app/node_modules
RUN mkdir -p /app/node_modules/.cache && chmod 777 /app/node_modules/.cache

WORKDIR /app

COPY package*.json ./
RUN npm install

# Мы не копируем исходники, так как они будут смонтированы как том
# Это позволит изменениям в исходниках сразу отражаться

EXPOSE 3000

# Запуск от имени обычного пользователя вместо root
USER node 

CMD ["npm", "start"] 