version: '3.8'

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    restart: always

  backend:
    build: ./backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    volumes:
      - frontend_build:/app/build/
    depends_on:
      - backend

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d/
      - ./nginx/ssl:/etc/nginx/ssl/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - frontend_build:/usr/share/nginx/html/
    depends_on:
      - backend
      - frontend
    restart: always

volumes:
  postgres_data:
  static_value:
  media_value:
  frontend_build: 