version: '3.8'

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    restart: always

  backend:
    build: ./backend
    restart: always
    ports:
      - "9009:9009"
    depends_on:
      - db
    env_file:
      - ./.env
    environment:
      - DEBUG=true
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:9009/api

volumes:
  postgres_data:
  static_value:
  media_value: 