# Generated by Django 4.2.7 on 2025-06-06 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('railway_crossings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='closure',
            name='digital_signature',
            field=models.TextField(blank=True, null=True, verbose_name='Цифровая подпись'),
        ),
        migrations.AddField(
            model_name='closure',
            name='signature_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата подписания'),
        ),
        migrations.CreateModel(
            name='ClosureDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название документа')),
                ('file', models.FileField(upload_to='closure_documents/%Y/%m/', verbose_name='Файл документа')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('document_type', models.CharField(choices=[('road_scheme', 'Схема организации дорожного движения'), ('approval', 'Согласование с другими службами'), ('contract', 'Договор на выполнение работ'), ('supporting', 'Сопроводительный документ'), ('other', 'Другое')], default='supporting', max_length=50, verbose_name='Тип документа')),
                ('closure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='railway_crossings.closure', verbose_name='Заявка на закрытие')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Загружено пользователем')),
            ],
            options={
                'verbose_name': 'Документ заявки',
                'verbose_name_plural': 'Документы заявок',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
